name: syntax tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit:
    name: Syntax unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        working-directory: ./fluent.syntax
        run: |
          python -m pip install wheel
          python -m pip install --upgrade pip
          python -m pip install six
      - name: Test
        working-directory: ./fluent.syntax
        run: |
          ./runtests.py
